name: BFF Project CICD

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/BFFs-cicd.yml@v1.4.9
    with:
      package_name: bff-project
      node_version: 20
    secrets: inherit